observation_space [Box(9,), Box(9,), Box(9,)]
share_observation_space [Box(27,), Box(27,), Box(27,)]
obs_space:  [Box(9,), Box(9,), Box(9,)]
share_obs_space:  [Box(27,), Box(27,), Box(27,)]
act_space:  Discrete(3)
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    main(sys.argv[1:])
  File "main.py", line 109, in main
    runner.run()
  File "/home/chunhuili/Transportation/RailEnvironment/MAPPO/runner/rail_runner.py", line 31, in run
    obs, rewards, dones, infos = self.envs.step(actions_env) # obs 32 3 9 rewards 32 3 dones 32 3 infos 32 3
  File "/home/chunhuili/Transportation/RailEnvironment/envs_wrappers.py", line 107, in step
    return self.step_wait()
  File "/home/chunhuili/Transportation/RailEnvironment/envs_wrappers.py", line 266, in step_wait
    results = [remote.recv() for remote in self.remotes]
  File "/home/chunhuili/Transportation/RailEnvironment/envs_wrappers.py", line 266, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/home/chunhuili/anaconda3/envs/transport/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/chunhuili/anaconda3/envs/transport/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/chunhuili/anaconda3/envs/transport/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
